### ISSUE TITLE
Question regarding content_type in front matter

### ISSUE THREAD

**Issue by robbiecloset** [contentful-labs/contentful-metalsmith-example#1]
Hey @madtrick, just experimenting with getting a site up and running with Contentful & Metalsmith. Mostly working well, but I've noticed that, under the hood, when I try to filter entries by content_type, it only works if I provide the id, as opposed to the name. 

To be fair, [that is what the API documentation says](https://www.contentful.com/developers/documentation/content-delivery-api/javascript/#searching-entries), however, the example source files ([here](https://github.com/contentful/contentful-metalsmith-example/blob/master/src/albums.html#L5) & [here](https://github.com/contentful/contentful-metalsmith-example/blob/master/src/venues.html#L5)) in this repo led me to believe that a name would be sufficient. 

No biggie if the ID is required in the front matter, I just want to make sure I'm not missing something. 

Thanks!

**Comment by madtrick** [comment]
Hi,

As you have already pointed, you always have to provide the `content_type` id when filtering. On the examples that you mention we are actually using the `content_type` id. Only that on this case it has been modified to be a 'better looking' id. But an id anyway.

If we query the API for a description of the Album `content_type` we can see that its id is in fact 'album':

``` bash
$ http https://cdn.contentful.com/spaces/ntaqqv7rma1o/content_types/album access_token==b617ee1f8cd5968823d5ea8aa63fbadb92ce65f2ef9c6f64cee6a5b184111279
...
{
    "displayField": "title",
    "fields": [
       ...
    ],
    "name": "Album",
    "sys": {
        "createdAt": "2014-05-12T16:20:29.316Z",
        "id": "album",
        "revision": 6,
        "space": {
         ...
        },
        "type": "ContentType",
        "updatedAt": "2014-06-19T16:04:29.416Z"
    }
```

Hope this helps
