### ISSUE TITLE
Handlebars sort

### ISSUE THREAD

**Issue by m1skam** [contentful-labs/contentful-metalsmith-example#4]
Hello.
I have a question. I'm using lists of data from several spaces on a page of mine. There's a neccessity to sort these lists and limit the number of input elements. Could you please share an example of how exactly I could use handlebars to make that? I tried it out with {{withSort}} but failed to make it work. I was planning to use raiting in one case and digits in another one to sort the lists.

**Comment by stefanjudis** [comment]
@m1skam Hey hey,

I'll have a look at it tomorrow. 

> There's a neccessity to sort these lists and limit the number of input elements

Number of input elements? I'm not sure I understand what you mean. :)

If you could provide a bit more detail on your configuration, that would be helpful so that I can provide the same scenario. :)

**Comment by stefanjudis** [comment]
@m1skam 

I added a new file in `helpers` to have a new handlebars helper available.

https://github.com/contentful-labs/contentful-metalsmith-example/blob/master/helpers/eachSortedByTitle.js#L1-L19

I used this then to sort the categories by title. 

https://github.com/contentful-labs/contentful-metalsmith-example/blob/master/partials/articleHeader.html#L28-L30

This is not as generic as it could be but I guess using helpers, it would be also possible to hand in a property to sort for. :)

I hope this answers your question and helps you getting started?

**Comment by m1skam** [comment]
@stefanjudis
Sorry for the answer delay.Thank you so much for the sorting helper.

Let me illustrate two of the problems I faced with in the real project.

The example of data I get into my project is JSON of one element,I got the consoles with the {{debug this}} helper

``` JSON
value: {
  "sys": {
    "space": {
      "sys": {
        "type": "Link",
        "linkType": "Space",
        "id": "..."
      }
    },
    "id": "...",
    "type": "Entry",
    "createdAt": "2016-09-13T10:33:56.814Z",
    "updatedAt": "2016-09-21T15:36:21.523Z",
    "revision": 3,
    "contentType": {
      "sys": {
        "type": "Link",
        "linkType": "ContentType",
        "id": "people"
      }
    },
    "locale": "ru-RU"
  },
  "fields": {
    "name": "Name One",
    "personRating": 10,
    "conferences": [{
      "sys": {
        "space": {
          "sys": {
            "type": "Link",
            "linkType": "Space",
            "id": "..."
          }
        },
        "id": "...",
        "type": "Entry",
        "createdAt": "2016-09-13T09:31:11.204Z",
        "updatedAt": "2016-09-21T15:16:34.618Z",
        "revision": 2,
        "contentType": {
          "sys": {
            "type": "Link",
            "linkType": "ContentType",
            "id": "conferences"
          }
        },
        "locale": "ru-RU"
      },
      "fields": {
        "name": "2016",
        "slug": "2016"
      }
    }]
  }
}
```

Trouble 1. 
"conferences" is a field with Many References type.When the field type is just References,I can filter the data with a simple helper:

``` javascript
Handlebars.registerHelper('if_eq', function(a, b, opts) {
  if (a == b) {
      return opts.fn(this);
  } else {
      return opts.inverse(this);
  }
});
```

``` html
{{#if_eq fields.conferences.fields.name '2016'}}
  ...
{{/if_eq}}
```

Unfortunately this hepler doesn't work if the field type is Many References

Trouble 2
Let's say I have 100 articles, but I would like to display only first 10 of them

**Comment by stefanjudis** [comment]
Hey hey. :)

## Trouble 1

Not sure if I get this completely. You got a collection of many conference.
Could you register another helper? Similar to the one I shared?

When I got it right, you want to loop over collection and  only render items matching a fields value a particular value?

`helperFn`

```
module.exports = function (context, value, options) {
  var ret = ''

  var filteredContext = context.filter(function (item) {
    console.log(item.fields.title);
    return item.fields.title === value;
  })

  for (var i = 0, j = filteredContext.length; i < j; i++) {
    ret = ret + options.fn(filteredContext[i])
  }

  return ret
}
```

`Template`

```
{{#eachFilterByTitle category 'Literature' }}
  <li>{{ fields.title }}
{{/eachSortedByTitle}}
```

## Trouble 2

You could do the same with another helper and slice the Array. :)

I hope this helps. Let me know, if you have further troubles.

**Comment by m1skam** [comment]
Thanks a lot for your help.
