### ISSUE TITLE
encoding problems with data-markdown

### ISSUE THREAD

**Issue by m1skam** [contentful-labs/contentful-metalsmith-example#6]
Hi,

I faced a problem with 'metalsmith-data-markdown' package. This package converts all Cyrillic characters into decimal HTML codes.

This 

```
Ознакомление со всеми модулями
```

 is converted

```
&#x41E;&#x437;&#x43D;&#x430;&#x43A;
&#x43E;&#x43C;&#x43B;&#x435;&#x43D;
&#x438;&#x435; &#x441;&#x43E; &#x432;
&#x441;&#x435;&#x43C;&#x438; &#x43C;
&#x43E;&#x434;&#x443;&#x43B;&#x44F;
&#x43C;&#x438;
```

Are there any other variants for convert markdown?

**Comment by stefanjudis** [comment]
I used a different approach for my own website.

https://github.com/stefanjudis/stefan-judis-website/blob/master/helpers/marked.js

This way you can control marked itself.

Does this help?

**Comment by stefanjudis** [comment]
@m1skam 

Now that I think of this this is actually correct. It's nothing else than using e.g. `&amp;`.  It's to encode unsafe and non-ASCII characters.

It will work when served to browsers, or?
I tried it - and it looked fine.

👇  - edited the encoded characters.
![bildschirmfoto 2016-10-04 um 14 16 22](https://cloud.githubusercontent.com/assets/962099/19073835/816300d4-8a3d-11e6-98b1-1118a684394c.png)

👇  result in Google Chrome.
![bildschirmfoto 2016-10-04 um 14 16 30](https://cloud.githubusercontent.com/assets/962099/19073837/82b1a9ae-8a3d-11e6-8f52-ce1a04069a17.png)

**Comment by stefanjudis** [comment]
Closed due to inactivity.
