### ISSUE TITLE
Common Example Not Working

### ISSUE THREAD

**Issue by bhardy** [contentful-labs/contentful-metalsmith-example#7]
I might be mistaken, but I'm running a local instance of this project and everything seems to be working correctly except for the `{{ common.featured_author.items.0.fields.name }}` in `header.html`. Can anyone confirm?

**Comment by stefanjudis** [comment]
Is this still an issue?

It's working fine here...

![bildschirmfoto 2016-11-29 um 10 21 51](https://cloud.githubusercontent.com/assets/962099/20703871/b3db30d4-b61d-11e6-9aad-7f0bc294c90b.png)

**Comment by bhardy** [comment]
Sorry, didn't see your reply. I think it was an issue with the contentful version that was being installed or something. I created a project from scratch and it worked, but cloning this one wouldn't work for me.

**Comment by 01fade** [comment]
Hi, I just cloned this example and it doesn't work for me, there is no name shown after "New:"
I don't know how to actually start from scratch, so a fix would be really great! Thanks a lot!

**Comment by stefanjudis** [comment]
@bhardy @228miles Sorry for the inconvenience, I forgot to update the used version of contentful-metalsmith.

It should now work. I update `package.json` and removed the `shrinkwrap`.

Please reopen, when you're still having troubles.
